# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-28 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('image', models.TextField()),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('author', models.TextField()),
                ('website', models.TextField()),
                ('description', models.TextField()),
                ('pubtime', models.DateTimeField()),
            ],
        ),
    ]
